export const config = {
    DURATION: 30,
    TIMER: 5,
    ALPHABET: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
        'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
    LEVELS: [
        {id: 1, label: 'Lvl 1', range: [1, 3]},
        {id: 2, label: 'Lvl 2', range: [1, 3]},
        {id: 3, label: 'Lvl 3', range: [1, 3]},
        {id: 4, label: 'Lvl 4', range: [2, 4]},
        {id: 5, label: 'Lvl 5', range: [2, 4]},
        {id: 6, label: 'Lvl 6', range: [2, 4]},
        {id: 7, label: 'Lvl 7', range: [3, 5]},
        {id: 8, label: 'Lvl 8', range: [3, 5]},
        {id: 9, label: 'Lvl 9', range: [3, 5]},
        {id: 10, label: 'Lvl 10', range: [3, 5]},
        {id: 11, label: 'Lvl 11', range: [3, 5]},
        {id: 12, label: 'Lvl 12', range: [4, 6]},
        {id: 13, label: 'Lvl 13', range: [4, 6]},
        {id: 14, label: 'Lvl 14', range: [4, 6]},
        {id: 15, label: 'Lvl 15', range: [4, 6]},
        {id: 16, label: 'Lvl 16', range: [4, 6]},
        {id: 17, label: 'Lvl 17', range: [5, 7]},
        {id: 18, label: 'Lvl 18', range: [5, 7]},
        {id: 19, label: 'Lvl 19', range: [5, 7]},
        {id: 20, label: 'Lvl 20', range: [5, 7]},
    ]
}